from fuzzywuzzy import fuzz
import collections
x = ['please', 'select', 'open', 'cash', 'plus', 'for', 'mso', 'view', 'client', 'for', 'mso', 'enroll', 'in', 'mso', 'access', 'irs', 'form', 'for', 'mso', 'account', 'summary', 'for', 'mso', 'benefits', 'of', 'mso', 'wire', 'transfer', 'for', 'mso', 'householding', 'for', 'mso', 'ach', 'rejected', 'for', 'mso', 'view', 'payment', 'for', 'mso', 'create', 'list', 'for', 'mso', 'trade', 'confirmation', 'missing', 'for', 'mso', 'reset', 'password', 'for', 'mso', 'sell', 'equity', 'for', 'mso', 'contact', 'for', 'mso', 'access', 'mso', 'get', 'registration', 'code', 'for', 'mso', 'reverse', 'ach', 'for', 'mso', 'trade', 'not', 'processed', 'for', 'mso', 'alert', 'for', 'mso', 'register', 'for', 'mso', 'performance', 'reporting', 'for', 'mso', 'security', 'for', 'mso', 'statement', 'linking', 'for', 'mso', 'remove', 'username', 'for', 'mso', 'insufficient', 'funds', 'for', 'mso', 'tax', 'form', 'for', 'mso', 'update', 'username', 'for', 'mso', 'funds', 'alert', 'for', 'mso', 'eligible', 'for', 'trade', 'for', 'mso', 'how', 'to', 'find', 'householding', 'for', 'mso', 'how', 'to', 'add', 'performance', 'account', 'statement', 'for', 'mso', 'stock', 'screener', 'mso', 'options', 'screener', 'tool', 'mso', 'fixed', 'income', 'screen', 'tool', 'mso', 'browser', 'for', 'mso', 'tax', 'preparation', 'software', 'for', 'mso', 'watch', 'list', 'for', 'mso']
y = ['please', 'select', 'open', 'cash', 'plus', 'for', 'mso', 'view', 'client', 'for', 'mso', 'enroll', 'in', 'mso', 'access', 'irs', 'form', 'for', 'mso', 'account', 'summary', 'for', 'mso', 'benefits', 'of', 'mso', 'wire', 'transfer', 'for', 'mso', 'householding', 'for', 'mso', 'ach', 'rejected', 'for', 'mso', 'view', 'payment', 'for', 'mso', 'create', 'list', 'for', 'mso', 'trade', 'confirmation', 'missing', 'for', 'mso', 'reset', 'password', 'for', 'mso', 'sell', 'equity', 'for', 'mso', 'contact', 'for', 'mso', 'access', 'mso', 'get', 'registration', 'code', 'for', 'mso', 'reverse', 'ach', 'for', 'mso', 'trade', 'not', 'processed', 'for', 'mso', 'alert', 'for', 'mso', 'register', 'for', 'mso', 'performance', 'reporting', 'for', 'mso', 'security', 'for', 'mso', 'statement', 'linking', 'for', 'mso', 'remove', 'username', 'for', 'mso', 'insufficient', 'funds', 'for', 'mso', 'tax', 'form', 'for', 'mso', 'update', 'username', 'for', 'mso', 'funds', 'alert', 'for', 'mso', 'eligible', 'for', 'trade', 'for', 'mso', 'how', 'to', 'find', 'householding', 'for', 'mso', 'how', 'to', 'add', 'performance', 'account', 'statement', 'for', 'mso', 'stock', 'screener', 'mso', 'options', 'screener', 'tool', 'mso', 'fixed', 'income', 'screen', 'tool', 'mso', 'browser', 'for', 'mso', '', 'watch', 'list', 'for', 'mso', 'tax', 'preparation', 'software', 'for', 'mso']

print('--x-------',x)
print('--y-------',y)
print(collections.Counter(list(filter(None, x))) == collections.Counter(list(filter(None, y))))

#
#Result = Str1 == Str2
#print('---------',Result)